/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  future: {
    hoverOnlyWhenSupported: true,
  },
  safelist: [
    // Dynamic classes that might not be detected
    "bg-success",
    "bg-warning",
    "bg-danger",
    "bg-info",
    "bg-primary",
    "text-success",
    "text-warning",
    "text-danger",
    "text-info",
    "text-primary",
    "accent-success",
    // Blue gradient classes
    "bg-gradient-to-r",
    "from-blue-600",
    "to-blue-700",
    "from-blue-500",
    "to-blue-600",
    // Investigation Tab Gradients
    "bg-gradient-to-br",
    "via-blue-50/30",
    "to-indigo-50/50",
    "from-blue-600",
    "via-indigo-600",
    "to-blue-700",
    "from-white",
    "via-purple-50/30",
    "to-pink-50/50",
    "from-purple-600",
    "via-fuchsia-600",
    "to-purple-700",
    "from-amber-50",
    "to-orange-50",
    "from-amber-400",
    "to-orange-500",
    "from-rose-500",
    "to-pink-600",
    "from-red-500",
    "to-orange-600",
    "from-purple-500",
    "to-indigo-600",
    "from-blue-500",
    "to-cyan-600",
    "from-green-600",
    "to-emerald-600",
    "via-emerald-600",
    "to-green-700",
    // Frequency field gradient classes
    "from-purple-600",
    "via-purple-700",
    "to-pink-600",
    "border-purple-600",
    "bg-gradient-to-r",
    "from-green-50",
    "via-emerald-50",
    "to-teal-50",
    "from-indigo-600",
    "via-blue-600",
    "to-indigo-700",
    "from-amber-50",
    "via-yellow-50",
    "to-orange-50",
    "from-gray-50",
    "to-slate-50",
    // Opacity classes
    "bg-white/20",
    "bg-white/30",
    "hover:bg-white/30",
    // Text colors
    "text-white",
    "text-blue-100",
    "text-gray-700",
    "text-gray-800",
    "text-gray-900",
    // Background colors
    "bg-white",
    "bg-gray-50",
    "bg-blue-50",
    "bg-blue-100",
    "bg-blue-600",
    "bg-blue-700",
    "bg-red-100",
    "bg-green-100",
    "bg-pink-100",
    "bg-gray-100",
    // Investigation Tab Backgrounds
    "bg-indigo-50",
    "bg-indigo-100",
    "bg-indigo-600",
    "bg-indigo-700",
    "bg-purple-50",
    "bg-purple-100",
    "bg-purple-600",
    "bg-purple-700",
    "bg-fuchsia-600",
    "bg-fuchsia-700",
    "bg-amber-50",
    "bg-amber-100",
    "bg-amber-400",
    "bg-amber-500",
    "bg-orange-50",
    "bg-orange-500",
    "bg-orange-600",
    "bg-green-50",
    "bg-green-600",
    "bg-green-700",
    "bg-emerald-50",
    "bg-emerald-100",
    "bg-emerald-600",
    "bg-emerald-700",
    "bg-teal-50",
    "bg-rose-500",
    "bg-pink-600",
    "bg-cyan-600",
    "bg-slate-50",
    // Text colors for status
    "text-blue-800",
    "text-red-800",
    "text-green-800",
    "text-pink-800",
    // Investigation Tab Text Colors
    "text-blue-100",
    "text-purple-100",
    "text-amber-800",
    "text-amber-900",
    // Border colors
    "border-gray-200",
    "border-red-200",
    "border-green-200",
    // Investigation Tab Borders
    "border-blue-200",
    "border-blue-300",
    "border-blue-400",
    "border-indigo-200",
    "border-purple-200",
    "border-amber-200",
    "border-amber-300",
    "border-green-300",
    // Hover states
    "hover:bg-blue-50",
    "hover:bg-blue-700",
    "hover:bg-blue-200",
    "hover:bg-amber-100",
    "hover:bg-green-700",
    "hover:bg-purple-700",
    "hover:bg-indigo-700",
    "hover:bg-gray-600",
    "hover:bg-gray-700",
    "hover:border-blue-300",
    "hover:border-blue-400",
    "hover:shadow-lg",
    "hover:shadow-xl",
    "hover:scale-105",
    "hover:scale-102",
    // Shadows
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-inner",
    // Ring colors
    "focus:ring-2",
    "focus:ring-blue-200",
    "focus:border-blue-500",
    // Transform
    "transform",
    "scale-105",
    "transition-all",
    // Animation
    "animate-spin",
    "animate-pulse",
  ],
  theme: {
    extend: {
      colors: {
        // Theme Colors - Exact from HTML
        primary: {
          DEFAULT: "#0062ff",
          light: "#3d8bff",
          dark: "#0050d4",
        },
        secondary: {
          DEFAULT: "#8e94a9",
          light: "#a5aaba",
          dark: "#777d98",
        },
        success: "#44ce42",
        warning: "#ffc542",
        danger: "#fc5a5a",
        info: "#a461d8",
        dark: "#001737",
        light: "#aab2bd",

        // Base Colors from HTML
        blue: "#5E50F9",
        indigo: "#6610f2",
        purple: "#6a008a",
        pink: "#E91E63",
        red: "#f96868",
        orange: "#f2a654",
        yellow: "#f6e84e",
        green: "#46c35f",
        teal: "#58d8a3",
        cyan: "#57c7d4",
        violet: "#41478a",

        // Gray Scale
        gray: {
          DEFAULT: "#434a54",
          light: "#aab2bd",
          lighter: "#e8eff4",
          lightest: "#e6e9ed",
          dark: "#0f1531",
        },

        // Background Colors
        "content-bg": "#f0f1f6",
        "white-smoke": "#f2f7f8",
      },
      fontFamily: {
        ubuntu: ["Ubuntu", "sans-serif"],
        nunito: ["Nunito", "sans-serif"],
      },
    },
  },
  plugins: [],
};
